---
title: '2019-03-20'
author: ""
date: "3/20/2019"
output: html_document
---
```{r}
dialogue <- c('小明說："明天不用上課。"',
               '小花說："真的嗎？"')

cat(dialogue, sep="\n")
```
```{r}

```

```{r}
aLogical <- c,F,FALSE,FALSE)
class(aLogical)
```

```{r}。
sum(aLogical)
```
```{r}
sum(aLogical)
```

```{r}

```

```{r}
class(studentMajors)
```
```{r}
studentMajors <- factor(
  c("電機系", "經濟系", "法律系")
)
```

```{r}
studentMajors1<- factor(
  c("台北市", "高雄市", "宜蘭縣", "宜蘭縣")
)
```

```{r}
typeof(studentMajors)
```

```{r}
typeof(studentMajors1)
```


```{r}
levels(studentMajors1)
```
```{r}
as.integer(studentMajors1)
```
```{r}
stringInteger <- c("1","2","-11")
class(stringInteger) 
```

```{r}
library(lubridate)
```

```{r}
dtObject<-ymd_hms("1970-01-01 00:02:53") 
```

```{r}
dtObjectVector<-ymd_hms(
  c("1970-01-01 00:02:53",
    "1980-02-11 11:25:22")
)
```

```{r}
class(dtObject)
```

```{r}

```

```{r}
dtObject
```
```{r}
Sys.timezone()
```
```{r}
twDateTime <- ymd_hms("2019-03-18 14:04:00", tz="Asia/Taipei")

twDateTime 
```

```{r}
LisbonDateTime <- with_tz(twDateTime,tzone="Europe/Lisbon")

LisbonDateTime
```
```{r}
typeof(twDateTime)
as.double(twDateTime)
```
```{r}
nowdatetime <-mdy_hms("03-27-2019 15:53:27")

nowdatetime
```

```{r}
a <- c(1, 5, -3)
b <- c(0.5, 12, 2)
aL <- c(1L, 5L, -3L)
bL <- c(-2L, -4L, 8L)
```

```{r}
a+bL
aL+bL
```

```{r}
a^b
a %% b
```
```{r}
twDateTime <- ymd_hms("2019-03-18 14:04:00", tz="Asia/Taipei")

twDateTime
twDateTime+300
```

```{r}
startingDate <- ymd("2000-02-17")
```

```{r}
startingDate + years(25)
```

```{r}
startingDate + dyears(25)
```

```{r}
ymd("2000-02-01") -> startingDate
ymd("2019-08-11") -> endingDate
endingDate - startingDate
```

```{r}
x <- 5
y <- 7
```
```{r}
x2 <- c(1,5,10)
y2 <- c(-1,5,20)
```

```{r}
x3 <- c("小明","小花")
y3 <- c("小明","小華")
```
```{r}
x3==y3
x3!=y3
```
```{r}
x3==y3
!(x3==y3)
```

```{r}
0/0
```

```{r}
library(readr)
exData2 <- read_csv("https://raw.githubusercontent.com/tpemartin/github-data/master/exData2.csv")
currency <- exData2$幣別
```

