---
title: "2019-4-10"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
install.packages("stringr")
```

```{r}
library(stringr)
```

```{r}
course <- c("個體經濟學","投資學","總體經濟學")
str_detect(course,"經濟學")
```


```{r}
studentID<-c(
  '410177115','410176080','410174233','410177011','410182045','410176014')
```

```{r}
str_sub(studentID,5,6)
```
```{r}
studentID
str_sub(studentID,2,4)
```
```{r}
char1 <- c("月","月","月")
char2 <- c("日","日","日")
month<- c("3","7","9")
day<- c("3","7","9")
```
```{r}
str_c(month,"月",day,"日",sep="-")
```
```{r}
library(readr)
githubData <- read_csv("https://raw.githubusercontent.com/tpemartin/github-data/master/githubData.csv")
username <- githubData$`GitHub username`[11:16]
reponame <- githubData$`GitHub repo name`[11:16]
```

```{r}
username
reponame
```

```{r}
str_c("https://github.com/",username,"/",reponame)
```
```{r}
library(readr)
filmVotingData <- read_csv("https://raw.githubusercontent.com/tpemartin/github-data/master/%E7%AC%AC%E4%B8%89%E5%B1%86%E7%B6%93%E6%BF%9F%E6%92%AD%E5%AE%A2%E7%AB%B6%E8%B3%BD%E5%8F%83%E8%B3%BD%E4%BD%9C%E5%93%81%E6%8A%95%E7%A5%A8%E7%B5%90%E6%9E%9C%E6%A8%A3%E6%9C%AC%20-%20Sheet1.csv")
birthday<-filmVotingData$`出生西元年月日（驗證本人用）`
```
```{r}
Sys.getlocale()
```


